### ISSUE TITLE
Migrate org.

### ISSUE THREAD

**Issue by jackharrhy** [bluedrop-learning-networks/eslint-config-bluedrop#52]
It'd be nice to move projects here that are still active to public projects within our new org. https://github.com/bluedrop-learning-networks

**Comment by MitMaro** [comment]
There's a larger discussion that is needed on where our open source projects will live.

**Comment by MitMaro** [comment]
We had a chat internally about this and the decision was to move this project to the new organization as a public project.

**Comment by donalmacanri** [comment]
Repository migrated - need to switch from Travis CI to GitHub actions.
