### ISSUE TITLE
Disable `require-atomic-updates`

### ISSUE THREAD

**Issue by MitMaro** [bluedrop-learning-networks/eslint-config-bluedrop#62]
The `require-atomic-updates` rule is a great idea in principle, but it seems to be misbehaving a lot and providing a lot of false positives.

See: https://github.com/eslint/eslint/issues/11899

**Comment by dvalentiate** [comment]
I definitely had a false positive from this come up in some of my code as well.

**Comment by MitMaro** [comment]
I honestly thought I disabled it in my last round of updates.
