### ISSUE TITLE
Indent on empty lines

### ISSUE THREAD

**Issue by MitMaro** [bluedrop-learning-networks/eslint-config-bluedrop#9]
There was an option in JSCS (what tabs4life uses), includeEmptyLines, to require an indent on empty lines. It has been deprecated on JSCS and ESLint doesn't support it. (source: http://jscs.info/rule/validateIndentation)

If we still want this check we will need to find, build our own, or convince eslint to add it.

**Comment by dvalentiate** [comment]
weird that isn't is eslint. While I prefer it I think we can live without it.

**Comment by MitMaro** [comment]
@erinwu has been very adamant about having it. I am not strongly against or for, and not really willing to put in the work at the moment.

**Comment by erinwu** [comment]
I am not sure if we need to add it to the eslint as a rule. In some files, it's fine to not indent an empty line. But the files that both Jurko and I pointed out, they are regular files and we'd prefer to indent empty lines according to the previous line.

**Comment by MitMaro** [comment]
I think the ship has sailed on this issue. All of our projects now remove empty lines.
